env:
  es6: true
  node: true
extends: "eslint:recommended"
rules:
  eqeqeq:
    - 2
  no-console:
    - 0
  no-trailing-spaces: 1
  no-var: error
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-useless-escape:
    - 0
  prefer-arrow-callback: error
